### ISSUE TITLE
"omitKey" should have option to omit multiple keys.

### ISSUE THREAD

**Issue by mridulgelal** [laxmanpokhrel/xmanscript-utils#36]
to omit single key  we have delete keyword in TS but I was looking forward to a function that could do multiple omit at a time.

**Comment by laxmanpokhrel** [comment]
Thank you for your suggestion! @mridulgelal  TypeScript does provide a way to omit a single key from an object using the Omit utility type. However, if you're looking to omit multiple keys at once, you can easily achieve this by chaining multiple Omit operations together.
`// Omitting multiple keys by chaining the calls to omitKey
const omittedObject = omitKey(omitKey(omitKey(myObject, 'key1'), 'key2'), 'key3');` 
But yes, we'll surely modify the function to omit multiple keys by passing array of keys.
